<?php

return [
    'content' => [
        'meta' => [
            'title' => 'Baca Di Tebet - Perpustakaan & Ruang Kreatif',
            'description' => 'Perpustakaan, Library, Ruang Temu, Ruang Kreatif, Buku, Baca Buku, BDT, Baca di Tebet, Creative Space, Ruang Pikir, Ruang Baca',
        ],
        'nav' => [
            'items' => [
                ['label' => 'Tentang Kami', 'target' => 'about'],
                ['label' => 'Fasilitas', 'target' => 'facilities'],
                ['label' => 'Pendaftaran', 'target' => 'pricing'],
                ['label' => 'Agenda', 'target' => 'agenda'],
                ['label' => 'Blog', 'target' => 'blog'],
                ['label' => 'Kontak', 'target' => 'contact'],
            ],
            'cta' => 'Daftar Anggota',
        ],
        'hero' => [
            'badge' => 'Ruang untuk Tumbuh Bersama',
            'title_prefix' => 'Di Mana',
            'title_highlight' => 'Waktu Berhenti',
            'title_suffix' => 'dan Pikiran Mulai',
            'description_before' => 'Karena tidak semua yang berharga harus cepat. Di tengah hiruk-pikuk Jakarta, kami hadirkan ruang untuk',
            'description_highlight' => 'berpikir tenang, membaca mendalam, dan bertumbuh bersama',
            'description_after' => 'Lebih dari perpustakaan - ini adalah rumah kedua untuk jiwa pencari ilmu.',
            'primary_cta' => 'Gabung Sekarang',
            'secondary_cta' => 'Lihat Ruangan',
        ],
        'about' => [
            'title' => 'Salam Daya Baca',
            'quote' => '"Rendang yang nikmat tidak jadi dalam semalam. Begitu juga dengan pengetahuan, butuh proses panjang untuk meresap."',
            'paragraph_one' => 'BDT hadir sebagai alternatif dari ruang-ruang publik yang bersifat konsumeristik. Di saat dunia tergila-gila dengan kecanggihan dunia virtual. kami memilih menghadirkan sebuah ruang berbentuk perpustakaan fisik. Di tengah masyarakat yang mengglorifikasi kehidupan instan serta berorientasi pada hasil yang lebih penting daripada proses, kami mengajak masyarakat untuk berproses, dimulai dari membaca buku konvensional. Pengingat bahwa nasi yang ada di piring tidak terjadi begitu saja sebagaimana di dunia virtual. Ada proses panjang, mulai dari menanam padi hingga memasaknya. Seperti itu juga saat kita membaca sebuah buku, membaca satu persatu kata dari judul hingga penutup.',
            'paragraph_two_before' => 'BDT merupakan simbol pengingat bahwa selama masih memiliki raga, manusia tidak bisa terlepas dari proses manual. Dunia virtual tidak akan menghilangkan kebutuhan kita akan hal-hal dasar seperti makan, tidur, dan bernapas. Selain itu manusia sebagai makhluk sosial akan selalu membutuhkan interaksi tanpa sekat virtual.',
            'paragraph_two_highlight' => 'BDT bukan sekadar perpustakaan untuk menyimpan buku, tetapi untuk menyimpan, merawat dan mengembangkan pengetahuan.',
            'image' => 'images/ruang_baca.jpeg',
            'image_alt' => 'Interior Perpustakaan',
        ],
        'facilities' => [
            'title' => 'Fasilitas dan Ruangan',
            'description' => 'Dari zona hening untuk kontemplasi hingga ruang diskusi yang hidup. Semua ruangan dilengkapi AC, WiFi kencang, dan colokan listrik.',
            'items' => [
                [
                    'title' => 'Ruang Diskusi',
                    'description' => 'Terletak di lantai 1, area ini menyatu dengan kafe. Cocok untuk ngobrol santai sambil menikmati kopi.',
                    'image' => 'images/ruang_diskusi.jpeg',
                    'alt' => 'Ruang Diskusi',
                    'icon' => 'message-circle',
                    'badges' => ['Lantai 1', 'Social'],
                ],
                [
                    'title' => 'Ruang Roy B.B Janis',
                    'description' => 'Area terbesar (kapasitas 30-50 orang). Bisa untuk kerja, main piano, atau sewa event bedah buku dan konser mini.',
                    'image' => 'images/ruang_RBBJ.jpeg',
                    'alt' => 'Ruang Roy B.B Janis',
                    'icon' => 'music',
                    'badges' => ['Event', 'Piano', 'Kapasitas 50'],
                ],
                [
                    'title' => 'Ruang Baca (Hening)',
                    'description' => 'Zona hening total. Dilarang bicara dan makan. Hanya untuk membaca fokus dan belajar. Disediakan air minum.',
                    'image' => 'images/ruang_baca.jpeg',
                    'alt' => 'Ruang Baca',
                    'icon' => 'book-open',
                    'badges' => ['Quiet Zone', 'Fokus'],
                ],
                [
                    'title' => 'Ruang Pikir',
                    'description' => 'Ruangan favorit dengan dinding penuh buku dan meja marmer. Zona hening. Bisa disewa privat (maks 12 orang).',
                    'image' => 'images/ruang_pikir.jpeg',
                    'alt' => 'Ruang Pikir',
                    'icon' => 'battery-charging',
                    'badges' => ['Premium', 'Meeting'],
                ],
                [
                    'title' => 'Ruang Karya',
                    'description' => 'Ruang kedap suara untuk podcast atau konten kreator. Kapasitas 6 orang. Privasi terjaga.',
                    'image' => 'images/ruang_karya.jpeg',
                    'alt' => 'Ruang Karya',
                    'icon' => 'mic',
                    'badges' => ['Podcast', 'Soundproof'],
                ],
                [
                    'title' => 'Kafe Makan Di Tebet',
                    'description' => 'Lapar saat membaca? Nikmati burger, sop buntut, kopi, dan matcha latte di lantai 1.',
                    'image' => 'images/kafe_makan_di_tebet.png',
                    'alt' => 'Kafe Makan Di Tebet',
                    'icon' => 'coffee',
                    'badges' => ['Restoran', 'Coffee'],
                ],
            ],
            'rental' => [
                'title' => 'Ketentuan Sewa Ruangan',
                'items' => [
                    'Satu sesi = maksimum 3 jam.',
                    'Rp 500.000 / sesi (Ruang Pikir, Diskusi, Karya).',
                    'Rp 700.000 / sesi (Ruang Roy B.B. Janis).',
                    'Reservasi via WhatsApp.',
                ],
                'cta_label' => 'Booking Ruangan Sekarang',
            ],
        ],
        'pricing' => [
            'title' => 'Pilihan Keanggotaan',
            'description' => 'Pilih paket yang sesuai dengan kebutuhan membaca Anda. Dari kunjungan harian hingga akses tahunan penuh.',
            'faq_title' => 'Pertanyaan Umum',
            'faq_description' => 'Jawaban singkat untuk pertanyaan yang sering muncul.',
        ],
        'agenda' => [
            'title' => 'Agenda & Kegiatan',
            'description' => 'Bergabunglah dalam diskusi, bedah buku, dan berbagai kegiatan inspiratif di Baca Di Tebet.',
            'items' => [
                [
                    'status_label' => 'Event selesai',
                    'category' => 'BINCANG PUBLIK',
                    'title' => 'LIBERATING THE BODY POLITIC',
                    'subtitle' => 'Decolonizing Minds, Movements, and Motherlands',
                    'date' => 'Kamis, 15 Januari 2026 | 15.30 - 18.00 WIB',
                    'location' => 'Baca Di Tebet (Jl. Tebet Barat Dalam Raya No. 29)',
                    'description' => 'Diskusi publik internasional ini mempertemukan beragam perspektif lintas wilayah dan pengalaman untuk merefleksikan dekolonisasi. Menghadirkan Kanti W. Janis, Zayaan Shaafiu, Fanda Puspitasari, dan Christophe Dorigne-Thomson.',
                    'cta_label' => 'Pendaftaran Ditutup',
                    'cta_url' => 'https://bit.ly/BDT1501',
                    'image' => 'images/liberating-the-body-poltics.jpg',
                    'image_alt' => 'Poster Liberating The Body Politic',
                    'theme' => 'teal',
                    'is_active' => false,
                ],
                [
                    'status_label' => 'Event selesai',
                    'category' => 'BEDAH BUKU',
                    'title' => 'INSPIRASI KARTINI & KESETARAAN',
                    'subtitle' => 'Karya Prof. Dr. Wardiman Djojonegoro',
                    'date' => 'Jumat, 16 Januari 2026 | 14.00 - 17.00 WIB',
                    'location' => 'Baca Di Tebet (Perpustakaan & Ruang Temu)',
                    'description' => 'Menyelami Kartini sebagai pemikir yang relevan hingga hari ini. Bersama Kanti W. Janis, Stebby Julionatan, serta pembacaan surat oleh Mia Ismi dan Rizqika Arrum B.',
                    'cta_label' => 'Pendaftaran Ditutup',
                    'cta_url' => 'https://bit.ly/Kartini160126',
                    'image' => 'images/inspirasi-kartini-dan%20kesetaraan-gender.jpg',
                    'image_alt' => 'Poster Inspirasi Kartini',
                    'theme' => 'slate',
                    'is_active' => false,
                ],
            ],
        ],
        'blog' => [
            'title' => 'Tulisan Terbaru',
            'description' => 'Pemikiran, resensi, dan kabar dari komunitas BDT.',
            'cta_label' => 'Lihat Blog Selengkapnya',
        ],
        'contact' => [
            'title' => 'Informasi Kontak',
            'address_title' => 'Alamat',
            'address_lines' => [
                'Jl. Tebet Barat Dalam Raya No. 29,',
                'Tebet, Jakarta Selatan,',
                'DKI Jakarta',
            ],
            'email_title' => 'Email',
            'email' => 'bacaditebet@gmail.com',
            'instagram_title' => 'Social Media',
            'instagram_handle' => '@bacaditebet',
            'hours_title' => 'Jam Operasional',
            'hours' => [
                ['day' => 'Senin', 'time' => 'Tutup'],
                ['day' => 'Sel - Kamis', 'time' => '10:00 - 18:00 WIB'],
                ['day' => 'Jumat', 'time' => '12:30 - 21:00 WIB'],
                ['day' => 'Sabtu', 'time' => '10:00 - 22:00 WIB'],
                ['day' => 'Minggu', 'time' => '10:00 - 18:00 WIB'],
            ],
            'map_embed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.2087279435477!2d106.8470392!3d-6.236195299999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f3d2517ea14b%3A0xe276c06b5f3b3c3b!2sBaca%20Di%20Tebet%20Perpustakaan%20dan%20Ruang%20Temu!5e0!3m2!1sen!2sid!4v1768214840645!5m2!1sen!2sid',
        ],
        'footer' => [
            'privacy_label' => 'Privasi',
            'terms_label' => 'Syarat dan Ketentuan',
            'faq_label' => 'FAQ',
        ],
        'links' => [
            'whatsapp' => 'https://wa.me/62811889829',
            'whatsappGroup' => 'https://wa.me/62811889829?text=Halo%20Admin%2C%20saya%20ingin%20mendaftarkan%20rombongan%20ke%20BDT',
            'whatsappEvent' => 'https://wa.me/62811889829?text=Halo%20Admin%2C%20saya%20ingin%20konsultasi%20untuk%20mengadakan%20acara%20di%20BDT',
            'blog' => 'https://blog.bacaditebet.id',
            'email' => 'mailto:bacaditebet@gmail.com',
            'instagram' => 'https://instagram.com/bacaditebet',
        ],
        'faq_page' => [
            'title' => 'Pertanyaan Umum',
            'description' => 'Pertanyaan yang sering muncul seputar Baca Di Tebet.',
        ],
    ],
    'faq_items' => [
        [
            'question' => 'Siapa saja yang bisa bergabung di BDT?',
            'answer' => "- Minimal usia 12 tahun untuk menjadi anggota BDT.\n- Pelajar: siswa SMP dan SMA yang masih aktif bersekolah.\n- Mahasiswa: mahasiswa aktif hingga tingkat S1.\n- Umum: siapa saja selain pelajar dan mahasiswa S1.\n- Pembayaran dilakukan sesuai paket langganan yang dipilih.",
            'cta_label' => null,
            'cta_link_key' => null,
        ],
        [
            'question' => 'Apa saja fasilitas ruang yang tersedia?',
            'answer' => "- Ruang RBBJ (Roy B. B. Janis) / Ruang Temu: ruang santai yang memperbolehkan makanan dan minuman. Harap kembalikan buku ke troli setelah selesai membaca.\n- Ruang Pikir dan Ruang Baca: silent room khusus untuk fokus belajar. Makanan, minuman, dan komunikasi (telepon atau zoom) tidak diperbolehkan.\n- Ruang Karya: ruang eksklusif yang dapat diakses dengan perjanjian terlebih dahulu.",
            'cta_label' => null,
            'cta_link_key' => null,
        ],
        [
            'question' => 'Bagaimana cara mendaftar dan masuk ke BDT?',
            'answer' => "Mudah banget. Cukup 3 langkah:\n- Pilih paket: tentukan paket yang sesuai kebutuhan Anda.\n- Isi formulir: lengkapi data pendaftaran dengan benar.\n- Bayar: lakukan pembayaran sesuai paket yang dipilih.\nCatatan: tiket harian hanya berlaku untuk hari yang sama dengan pemesanan.",
            'cta_label' => null,
            'cta_link_key' => null,
        ],
        [
            'question' => 'Metode pembayaran apa saja yang tersedia?',
            'answer' => "Kami menyediakan berbagai metode pembayaran yang mudah:\n- Transfer bank: melalui virtual account.\n- E-wallet: GoPay, OVO, Dana, dan lainnya.\n- Minimarket: Alfamart, Indomaret.\n- Cash: langsung di lokasi (untuk tiket harian).\nSemua proses pembayaran aman dan terpercaya.",
            'cta_label' => null,
            'cta_link_key' => null,
        ],
        [
            'question' => 'Bagaimana cara menuju BDT dengan transportasi umum?',
            'answer' => "Lokasi BDT sangat mudah dijangkau. Berikut rute terbaiknya:\n- KRL Commuter Line: turun di Stasiun Cawang, lanjut dengan ojek online atau jalan kaki 15 menit.\n- TransJakarta: turun di Halte Pancoran Tugu, lanjut dengan ojek online atau jalan kaki 20 menit.\n- Kendaraan pribadi: alamat Jl. Tebet Barat Dalam Raya No. 29, Tebet, Jakarta Selatan.\nTips: gunakan Google Maps dengan kata kunci \"Baca Di Tebet\" untuk navigasi yang akurat.",
            'cta_label' => null,
            'cta_link_key' => null,
        ],
        [
            'question' => 'Bagaimana proses menjadi anggota BDT?',
            'answer' => "Bergabung sebagai anggota memberikan banyak keuntungan.\n- Pilih durasi: paket bulanan, 3 bulanan, atau tahunan.\n- Lengkapi data: isi formulir pendaftaran dengan lengkap.\n- Nikmati benefit: akses unlimited dan pinjam buku pulang.\n- Fleksibilitas waktu: datang kapan saja sesuai keinginan.\nAnggota bisa datang kapan saja (kecuali hari libur) selama masa berlaku.",
            'cta_label' => null,
            'cta_link_key' => null,
        ],
        [
            'question' => 'Bisakah membawa rombongan atau grup ke BDT?',
            'answer' => "Tentu saja. Kami menyambut kunjungan rombongan dengan paket khusus.\n- Rombongan sekolah: ideal untuk field trip edukatif.\n- Grup kantor: cocok untuk team building dan workshop.\n- Keluarga besar: gathering sambil membaca bersama.\nHubungi admin sekarang: Chat WhatsApp untuk konsultasi dan penawaran khusus rombongan.",
        ],
        [
            'question' => 'Bisakah mengadakan acara atau event di BDT?',
            'answer' => "BDT cocok untuk berbagai jenis acara.\n- Book launch dan bedah buku: suasana mendukung diskusi.\n- Workshop dan seminar: pelatihan menulis, literasi, dan pengembangan diri.\n- Book club meeting: pertemuan rutin komunitas pecinta buku.\n- Pameran dan exhibition: showcase karya seni, foto, atau hasil karya kreatif.\n- Study group: sesi belajar bersama dan diskusi akademik.\n- Community gathering: acara komunitas dan networking.\nFasilitas yang tersedia: Ruang serbaguna, proyektor, sound system, WiFi cepat, dan suasana yang inspiratif.\nTertarik mengadakan acara? Hubungi kami untuk diskusi konsep acara dan penawaran khusus.",
        ],
    ],
];

